apiVersion: v1
kind: Service
metadata:
  name: {{ include "twitter-app.fullname" . }}-frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.port }}
  selector:
    app: {{ include "twitter-app.name" . }}-frontend
